# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503620418b166e7073d67f87d432f73891a82f655c00468ff724da2675b4f8e9945af7a75b66cb69022bfa0c59cc7f48f73a96a1d06a9af3d10674f05e4b6ae1

test:
  secret_key_base: 5163abfbc12b5e9ca3980d383a9d57bb1a8a9b089163ee03a59072251b33e1c842c3feab38176364f7c9943d72655980b014edf36fef22888098afbb9485c133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
